### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by shermilaguerra** [DeagaDH/Buscador_JUCESP#1]
Bruno, por gentileza talvez vc me pode ajudar? seu código a primeira vez captura a imagem do captcha, depois  não captura mais a imagem.

**Comment by DeagaDH** [comment]
Oi Shermila. A ideia é que apareça o captcha como uma janela separada durante a execução. Do jeito que o código está feito, ele tira um print screen da tela inteira e recorda só o pedaço correspondente ao captcha (por isso pegar a localização e tamanho da figura). Vi que vc fechou a issue, então espero que tenha conseguido entender. Se ainda estiver com problemas, abra de novo e eu vejo o que pode estar dando problema.

**Comment by shermilaguerra** [comment]
Seu código a primeira vez que vc roda captura a imagem depois não captura a imagem, melhoramos seu código, capturando o path da imagem, para evitar esse problema. Agora estou atras de quebrar o captcha.
            var=captcha_im.get_attribute("src")  
            urllib.request.urlretrieve(var, id_image)
